<?php
namespace app\middleware\console;

use library\Middleware\Interfacer;

class typeMiddle extends Interfacer
{
    public function handle()
    {
        parent::handle(); // TODO: Change the autogenerated stub
    }
}